<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" total="4" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Surefire suite" duration-ms="218" started-at="2021-10-22T14:08:12Z" finished-at="2021-10-22T14:08:12Z">
    <groups>
    </groups>
    <test name="Surefire test" duration-ms="218" started-at="2021-10-22T14:08:12Z" finished-at="2021-10-22T14:08:12Z">
      <class name="semillero.pruebasUnitarias.OperacionesComicsTest">
        <test-method status="FAIL" signature="comprobarListadoComicsActivos()[pri:0, instance:semillero.pruebasUnitarias.OperacionesComicsTest@2d554825]" name="comprobarListadoComicsActivos" duration-ms="137" started-at="2021-10-22T09:08:12Z" finished-at="2021-10-22T09:08:12Z">
          <exception class="junit.framework.AssertionFailedError">
            <message>
              <![CDATA[expected:<ACTIVO> but was:<ACTIVO>]]>
            </message>
            <full-stacktrace>
              <![CDATA[junit.framework.AssertionFailedError: expected:<ACTIVO> but was:<ACTIVO>
	at junit.framework.Assert.fail(Assert.java:50)
	at junit.framework.Assert.failNotEquals(Assert.java:287)
	at junit.framework.Assert.assertEquals(Assert.java:67)
	at junit.framework.Assert.assertEquals(Assert.java:74)
	at semillero.pruebasUnitarias.OperacionesComicsTest.comprobarListadoComicsActivos(OperacionesComicsTest.java:77)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:135)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:193)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:94)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:146)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:379)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:340)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:125)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:413)
]]>
            </full-stacktrace>
          </exception> <!-- junit.framework.AssertionFailedError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- comprobarListadoComicsActivos -->
        <test-method status="FAIL" signature="comprobarListadoComicsInactivos()[pri:0, instance:semillero.pruebasUnitarias.OperacionesComicsTest@2d554825]" name="comprobarListadoComicsInactivos" duration-ms="1" started-at="2021-10-22T09:08:12Z" finished-at="2021-10-22T09:08:12Z">
          <exception class="junit.framework.AssertionFailedError">
            <message>
              <![CDATA[expected:<INACTIVO> but was:<INACTIVO>]]>
            </message>
            <full-stacktrace>
              <![CDATA[junit.framework.AssertionFailedError: expected:<INACTIVO> but was:<INACTIVO>
	at junit.framework.Assert.fail(Assert.java:50)
	at junit.framework.Assert.failNotEquals(Assert.java:287)
	at junit.framework.Assert.assertEquals(Assert.java:67)
	at junit.framework.Assert.assertEquals(Assert.java:74)
	at semillero.pruebasUnitarias.OperacionesComicsTest.comprobarListadoComicsInactivos(OperacionesComicsTest.java:127)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:135)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:193)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:94)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:146)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:379)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:340)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:125)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:413)
]]>
            </full-stacktrace>
          </exception> <!-- junit.framework.AssertionFailedError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- comprobarListadoComicsInactivos -->
      </class> <!-- semillero.pruebasUnitarias.OperacionesComicsTest -->
      <class name="semillero.pruebasUnitarias.OperacionesAritmeticasTest">
        <test-method status="PASS" signature="inicializar()[pri:0, instance:semillero.pruebasUnitarias.OperacionesAritmeticasTest@64616ca2]" name="inicializar" is-config="true" duration-ms="35" started-at="2021-10-22T09:08:12Z" finished-at="2021-10-22T09:08:12Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- inicializar -->
        <test-method status="PASS" signature="inicializar()[pri:0, instance:semillero.pruebasUnitarias.OperacionesComicsTest@2d554825]" name="inicializar" is-config="true" duration-ms="2" started-at="2021-10-22T09:08:12Z" finished-at="2021-10-22T09:08:12Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- inicializar -->
        <test-method status="PASS" signature="validarResultadoSumaExitoso()[pri:0, instance:semillero.pruebasUnitarias.OperacionesAritmeticasTest@64616ca2]" name="validarResultadoSumaExitoso" duration-ms="4" started-at="2021-10-22T09:08:12Z" finished-at="2021-10-22T09:08:12Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validarResultadoSumaExitoso -->
        <test-method status="PASS" signature="validarResultadoSumaFallido()[pri:0, instance:semillero.pruebasUnitarias.OperacionesAritmeticasTest@64616ca2]" name="validarResultadoSumaFallido" duration-ms="1" started-at="2021-10-22T09:08:12Z" finished-at="2021-10-22T09:08:12Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- validarResultadoSumaFallido -->
        <test-method status="PASS" signature="finalizaPruebasUnitarias()[pri:0, instance:semillero.pruebasUnitarias.OperacionesAritmeticasTest@64616ca2]" name="finalizaPruebasUnitarias" is-config="true" duration-ms="1" started-at="2021-10-22T09:08:12Z" finished-at="2021-10-22T09:08:12Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- finalizaPruebasUnitarias -->
      </class> <!-- semillero.pruebasUnitarias.OperacionesAritmeticasTest -->
    </test> <!-- Surefire test -->
  </suite> <!-- Surefire suite -->
</testng-results>
